/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.auth0:java-jwt:4.4.0")
    implementation(libs.io.javalin.javalin)
    implementation(libs.org.slf4j.slf4j.simple)
    implementation(libs.net.dv8tion.jda)
    implementation(libs.org.xerial.sqlite.jdbc)
    compileOnly(libs.io.papermc.paper.paper.api)
}

group = "com.hydraz"
version = "1.0-SNAPSHOT"
description = "HydrazStore"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.shadowJar {
    relocate("io.javalin", "com.hydraz.store.libs.javalin")
    relocate("net.dv8tion.jda", "com.hydraz.store.libs.jda")
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

